In [8]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("reservoirs.csv")

display(df.head())

,dato_Id,omrType,omrnr,iso_aar,iso_uke,fyllingsgrad,kapasitet_TWh,fylling_TWh,neste_Publiseringsdato,fyllingsgrad_forrige_uke,endring_fyllingsgrad
0,1995-09-03,EL,4,1995,35,0.944721,21.079208,19.913979,0001-01-01T00:00:00,0.936888,0.007833
1,2020-11-15,EL,1,2020,46,0.974361,6.003264,5.849344,2020-11-25T13:00:00,0.997406,-0.023046
2,2011-08-28,EL,4,2011,34,0.786499,21.079208,16.578772,0001-01-01T00:00:00,0.787193,-0.000694
3,1998-07-05,EL,3,1998,27,0.793969,8.920932,7.082947,0001-01-01T00:00:00,0.733812,0.060157
4,2011-03-27,EL,4,2011,12,0.300820,21.079208,6.341054,0001-01-01T00:00:00,0.311122,-0.010301

In [4]:
df.shape

(14877, 11)

In [9]:
# -----------------------------------------------------------------------------
# IND320 – Project Work, Part 1
# Jupyter Notebook: reading, cleaning, and plotting reservoirs.csv
# -----------------------------------------------------------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Nicer default plot style
plt.rcParams.update({
    "figure.figsize": (12, 5),
    "axes.grid": True,
    "grid.alpha": 0.3,
    "axes.titlesize": 12,
    "axes.labelsize": 10,
})

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 160)

In [6]:
# -----------------------------------------------------------------------------
# 1) Read reservoirs.csv with Pandas
# Location: D2Dbook/data/reservoirs.csv (relative to notebook)
# -----------------------------------------------------------------------------

csv_path = "reservoirs.csv"
df_raw = pd.read_csv(csv_path)

print(f"Rows: {df_raw.shape[0]:,}  |  Columns: {df_raw.shape[1]}")
df_raw.head()

Rows: 14,877  |  Columns: 11

,dato_Id,omrType,omrnr,iso_aar,iso_uke,fyllingsgrad,kapasitet_TWh,fylling_TWh,neste_Publiseringsdato,fyllingsgrad_forrige_uke,endring_fyllingsgrad
0,1995-09-03,EL,4,1995,35,0.944721,21.079208,19.913979,0001-01-01T00:00:00,0.936888,0.007833
1,2020-11-15,EL,1,2020,46,0.974361,6.003264,5.849344,2020-11-25T13:00:00,0.997406,-0.023046
2,2011-08-28,EL,4,2011,34,0.786499,21.079208,16.578772,0001-01-01T00:00:00,0.787193,-0.000694
3,1998-07-05,EL,3,1998,27,0.793969,8.920932,7.082947,0001-01-01T00:00:00,0.733812,0.060157
4,2011-03-27,EL,4,2011,12,0.300820,21.079208,6.341054,0001-01-01T00:00:00,0.311122,-0.010301

In [7]:
# -----------------------------------------------------------------------------
# 2) Rename columns to English / understandable names
# -----------------------------------------------------------------------------
# Original (Norwegian)  → New (English)
#   dato_Id                     → date
#   omrType                     → area_type       ("EL", "NO", "VASS")
#   omrnr                       → area_nr         (1–5 for EL, 0 for aggregates)
#   iso_aar                     → iso_year
#   iso_uke                     → iso_week
#   fyllingsgrad                → fill_ratio      (0–1, fraction of capacity)
#   kapasitet_TWh               → capacity_TWh    (total reservoir capacity)
#   fylling_TWh                 → filled_TWh      (currently stored energy)
#   neste_Publiseringsdato      → next_publication
#   fyllingsgrad_forrige_uke    → fill_ratio_prev_week
#   endring_fyllingsgrad        → fill_ratio_change
# -----------------------------------------------------------------------------

rename_map = {
    "dato_Id": "date",
    "omrType": "area_type",
    "omrnr": "area_nr",
    "iso_aar": "iso_year",
    "iso_uke": "iso_week",
    "fyllingsgrad": "fill_ratio",
    "kapasitet_TWh": "capacity_TWh",
    "fylling_TWh": "filled_TWh",
    "neste_Publiseringsdato": "next_publication",
    "fyllingsgrad_forrige_uke": "fill_ratio_prev_week",
    "endring_fyllingsgrad": "fill_ratio_change",
}

df = df_raw.rename(columns=rename_map).copy()
df.columns.tolist()

['date',
 'area_type',
 'area_nr',
 'iso_year',
 'iso_week',
 'fill_ratio',
 'capacity_TWh',
 'filled_TWh',
 'next_publication',
 'fill_ratio_prev_week',
 'fill_ratio_change']

In [10]:
# Standard libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Make plots a bit larger and readable in the notebook
plt.rcParams["figure.figsize"] = (12, 4)
plt.rcParams["axes.grid"] = True

In [11]:
# Load the reservoir data. The file is located in D2Dbook/data/reservoirs.csv
df = pd.read_csv("reservoirs.csv")

# Rename to English, understandable names
rename_map = {
    "dato_Id": "date",
    "omrType": "region_type",
    "omrnr": "region_number",
    "iso_aar": "iso_year",
    "iso_uke": "iso_week",
    "fyllingsgrad": "fill_fraction",
    "kapasitet_TWh": "capacity_TWh",
    "fylling_TWh": "fill_TWh",
    "neste_Publiseringsdato": "next_publication_date",
    "fyllingsgrad_forrige_uke": "fill_fraction_prev_week",
    "endring_fyllingsgrad": "fill_fraction_change",
}
df = df.rename(columns=rename_map)

# Parse dates (some are placeholder 0001-01-01)
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df["next_publication_date"] = pd.to_datetime(
    df["next_publication_date"], errors="coerce"
)

df.head()

C:\Users\Khali\AppData\Local\Temp\ipykernel_39844\1700062958.py:22: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["next_publication_date"] = pd.to_datetime(

,date,region_type,region_number,iso_year,iso_week,fill_fraction,capacity_TWh,fill_TWh,next_publication_date,fill_fraction_prev_week,fill_fraction_change
0,1995-09-03,EL,4,1995,35,0.944721,21.079208,19.913979,NaT,0.936888,0.007833
1,2020-11-15,EL,1,2020,46,0.974361,6.003264,5.849344,2020-11-25 13:00:00,0.997406,-0.023046
2,2011-08-28,EL,4,2011,34,0.786499,21.079208,16.578772,NaT,0.787193,-0.000694
3,1998-07-05,EL,3,1998,27,0.793969,8.920932,7.082947,NaT,0.733812,0.060157
4,2011-03-27,EL,4,2011,12,0.300820,21.079208,6.341054,NaT,0.311122,-0.010301